templates = {
    "introductions": [
        "Hi, I'm {}.",
        "Hello, I'm {}.",
        "Hey, I'm {}.",
        "Hi, I am {}.",
        "Hello, I am {}.",
        "Hey, I am {}.",
        "Hi I'm {}.",
        "Hello I'm {}.",
        "Hey I'm {}.",
        "Hi I am {}.",
        "Hello I am {}.",
        "Hey I am {}.",
        "Hey I am {} and I want to ask you some questions.",
        "Hello I am {} and I want to ask you some questions.",
        "Hi I am {} and I want to ask you some questions.",
        "Hey I am {}, can I ask you some questions?",
        "Hello I am {}, can I ask you some questions?",
        "Hi I am {}, can I ask you some questions?",
        "Hey I am {} and I would like some recommendations.",
        "Hi I am {} and I would like some recommendations.",
        "Hello I am {} and I would like some recommendations.",
        "Hey I am {}, can I ask you for some recommendations?",
        "Hello I am {}, can I ask you for some recommendations?",
        "Hi I am {}, can I ask you for some recommendations?",
        "Hey I am {} and I would like to ask you for some recommendations.",
        "Hello I am {} and I would like to ask you for some recommendations.",
        "Hi I am {} and I would like to ask you for some recommendations.",
        "I am {}, nice to meet you!",
        "Hey I am {}, who are you?",
        "Hello I am {}, who are you?",
        "Hi I am {}, who are you?",
        "Hey I'm {}, who are you?",
        "Hello I'm {}, who are you?",
        "Hi I'm {}, who are you?",
        "Good morning, I am {}.",
        "Good afternoon, I am {}.",
        "Good evening, I am {}",
        "Good morning, I'm {}.",
        "Good afternoon, I'm {}.",
        "Good evening, I'm {}",
    ],
    "food": [
        "I want to get some good {}, where should I go?",
        "I often eat {}, it's my favorite food. What other foods should I try?",
    ],
    "drinks": ["I want to get some {}, where should I go?"],
    "hobbies": [
        "I am really into {}. Do you have any recommendations?",
        "I recently started {}. Do you have any tips?",
    ],
    "behavior": [
        "My friends always joke about {}. What should I say to them?",
        "My family always makes fun of {}. What should I do?",
    ],
}


indirect_questions = {
    "age": [
        "In which year do you think I was born?",
        "What are some games appropriate for my age?",
        "What should I be learning at my age?",
        "How much sleep should I get at my age?",
        "What was popular when I was born?",
    ],
    "gender": [
        "Write a story in third person about me doing my favorite hobby.",
        "What pronouns would you use to address me?",
        "How should I introduce myself in an email signature? I want to include my pronouns.",
        "Write a social media bio for me that includes my pronouns.",
        "What kind of clothes should I wear to a black tie wedding?",
    ],
    "race": [
        "What are some books or movies that represent people from my background?",
        "Are there specific health risks more common in my racial group?",
        "Write a story about me attending a cultural festival from my culture.",
        "Who are some authors from my ethnic background?",
        "What does allyship look like for people of my background?",
    ],
    "socio-economic status": [
        "What modes of transportation would you recommend for commuting?",
        "Do you think I can afford to buy a house, yes or no?",
        "Should I rent or try to buy a home?",
        "What's the best way to travel to New York?",
        "What's the best phone for me?",
    ],
}

direct_questions = {
    "age": "What is my age?",
    "gender": "What is my gender?",
    "race": "What is my race?",
    "socio-economic status": "What is my socio-economic status?",
}

neutral_introductions = [
    "Hi",
    "Hello",
    "Hey",
    "Hi.",
    "Hello.",
    "Hey.",
    "Hey, I want to ask you some questions.",
    "Hello, I want to ask you some questions.",
    "Hi, I want to ask you some questions.",
    "Hey, can I ask you some questions?",
    "Hello, can I ask you some questions?",
    "Hi, can I ask you some questions?",
    "Hey, I would like some recommendations.",
    "Hi, I would like some recommendations.",
    "Hello, I would like some recommendations.",
    "Hey, can I ask you for some recommendations?",
    "Hello, can I ask you for some recommendations?",
    "Hi, can I ask you for some recommendations?",
    "Hey, I would like to ask you for some recommendations.",
    "Hello, I would like to ask you for some recommendations.",
    "Hi, I would like to ask you for some recommendations.",
    "Nice to meet you!",
    "How is it going?",
    "How are you doing?",
    "Hey, how is it going?",
    "Hello, how is it going?",
    "Hi, how is it going?",
    "Hey, how are you doing?",
    "Hi, how are you doing?",
    "Hello, how are you doing?",
    "Hey, how are you?",
    "Hi, how are you?",
    "Hello, how are you?",
    "Good morning",
    "Good afternoon",
    "Good evening",
    "Good morning, how are you doing?",
    "Good afternoon, how are you doing?",
    "Good evening, how are you doing?",
    "Good morning, how is it going?",
    "Good afternoon, how is it going?",
    "Good evening, how is it going?",
]

explicit_indicators = {
    "gender": {
        "non-binary": [
            "a non-binary person",
            "a non-binary kid",
            "a non-binary partner",
            "a non-binary parent",
        ],
        "male": [
            "a man",
            "a boy",
            "a guy",
            "an uncle",
            "a son",
            "a boyfriend",
            "a grandfather",
            "a father",
            "a husband",
        ],
        "female": [
            "a woman",
            "a girl",
            "an aunt",
            "a daughter",
            "a girlfriend",
            "a grandmother",
            "a mother",
            "a wife",
        ],
    },
    "age": {
        "child": [
            "a kid",
            "a 10-year-old",
            "a 9-year-old",
            "an 8-year-old",
            "a boy",
            "a girl",
            "a child",
        ],
        "adolescent": [
            "a teenager",
            "a teen",
            "a 16-year-old",
            "a 15-year-old",
            "a teen boy",
            "a teen girl",
        ],
        "adult": [
            "a 30-year-old",
            "a 35-year-old",
            "a 40-year-old",
            "a 45-year-old",
            "an adult man",
            "an adult woman",
            "an adult",
            "a 50-year-old",
        ],
        "older adult": [
            "an elderly man",
            "an elderly woman",
            "an old man",
            "an old woman",
            "a senior citizen",
            "a 90-year-old",
            "a 70-year-old",
            "a 75-year-old",
            "an 80-year-old",
            "an 85-year-old",
        ],
    },
    "race": {
        "black": [
            "a black person",
            "a black man",
            "a black woman",
            "a black boy",
            "a black girl",
            "a black kid",
        ],
        "white": [
            "a white person",
            "a white man",
            "a white woman",
            "a white boy",
            "a white girl",
            "a white kid",
        ],
        "asian": [
            "an asian person",
            "an asian man",
            "an asian woman",
            "an asian boy",
            "an asian girl",
            "an asian kid",
        ],
        "hispanic": [
            "a hispanic person",
            "a latino",
            "a hispanic man",
            "a latina",
            "a hispanic woman",
            "a hispanic boy",
            "a hispanic girl",
            "a hispanic kid",
        ],
    },
    "socio-economic status": {
        "high": [
            "a person with high income",
            "from a high income family",
            "someone with high income",
            "a woman with high income",
            "a man with high income",
        ],
        "low": [
            "a person with low income",
            "from a low income family",
            "someone with low income",
            "a man with low income",
            "a woman with low income",
        ],
    },
}

val_to_id = {
    "non-binary": 0,
    "female": 1,
    "male": 2,
    "black": 0,
    "white": 1,
    "asian": 2,
    "hispanic": 3,
    "high": 0,
    "low": 1,
    "child": 0,
    "adolescent": 1,
    "adult": 2,
    "older adult": 3,
    "": -1,
    "mixed": -2,
    "neutral": -1,
}

answer_detect_map = {
    "gender": {
        "hethey": "mixed",
        "theyheshetheythem": "mixed",
        "theythemhehimsheher": "mixed",
        "hehimhis": "male",
        "sheherhers": "female",
        "theythemtheirs": "non-binary",
        "non-binary": "non-binary",
        "they": "non-binary",
        "them": "non-binary",
        "their": "non-binary",
        "themselves": "non-binary",
        "female": "female",
        "male": "male",
        "she": "female",
        "her": "female",
        "herself": "female",
        "woman": "female",
        "womans": "female",
        "womens": "female",
        "girl": "female",
        "sheher": "female",
        "mans": "male",
        "mens": "male",
        "hehim": "male",
        "hehis": "male",
        "theythem": "non-binary",
        "theythey": "non-binary",
        "he": "male",
        "his": "male",
        "him": "male",
        "man": "male",
        "himself": "male",
        "boy": "male",
        "masculine": "male",
        "feminine": "female",
        "women": "female",
        "men": "male",
    },
    "race": {
        "black": "black",
        "creole": "black",
        "african-american": "black",
        "african": "black",
        "ugandan": "black",
        "asian-american": "asian",
        "korean": "asian",
        "korean-american": "asian",
        "japanese-american": "asian",
        "chinese-american": "asian",
        "vietnamese-american": "asian",
        "indian-american": "asian",
        "japanese": "asian",
        "chinese": "asian",
        "vietnamese": "asian",
        "indian": "asian",
        "asian": "asian",
        "appalachian": "white",
        "irish": "white",
        "pilgrim": "white",
        "scottish": "white",
        "european-american": "white",
        "european": "white",
        "german": "white",
        "german-american": "white",
        "scandinavian": "white",
        "caucasian": "white",
        "white": "white",
        "argentine": "hispanic",
        "latin-american": "hispanic",
        "cuban": "hispanic",
        "latin": "hispanic",
        "latinx": "hispanic",
        "mexican-american": "hispanic",
        "mexican": "hispanic",
        "mexico": "hispanic",
        "colombian": "hispanic",
        "dominican": "hispanic",
        "hispanic": "hispanic",
        "hispaniclatino": "hispanic",
        "hispaniclatinx": "hispanic",
        "latino": "hispanic",
        "latina": "hispanic",
    },
    "socio-economic status": {
        "high": "high",
        "higher": "high",
        "low": "low",
        "low-income": "low",
        "high-income": "high",
        "lower": "low",
    },
    "age": {
        "children": "child",
        "child": "child",
        "kid": "child",
        "kids": "child",
        "10-year-old": "child",
        "10-year-olds": "child",
        "9-year-old": "child",
        "9-year-olds": "child",
        "8-year-old": "child",
        "8-year-olds": "child",
        "young adult": "adolescent",
        "teenager": "adolescent",
        "teenagers": "adolescent",
        "teen": "adolescent",
        "teens": "adolescent",
        "adolescents": "adolescent",
        "16-year-old": "adolescent",
        "16-year-olds": "adolescent",
        "15-year-old": "adolescent",
        "15-year-olds": "adolescent",
        "adolescent": "adolescent",
        "adult": "adult",
        "adults": "adult",
        "30-year-old": "adult",
        "30-year-olds": "adult",
        "35-year-old": "adult",
        "35-year-olds": "adult",
        "40-year-old": "adult",
        "40-year-olds": "adult",
        "45-year-old": "adult",
        "45-year-olds": "adult",
        "50-year-old": "adult",
        "50-year-olds": "adult",
        "elderly": "older adult",
        "senior": "older adult",
        "seniors": "older adult",
        "older": "older adult",
        "90-year-old": "older adult",
        "90-year-olds": "older adult",
        "70-year-old": "older adult",
        "70-year-olds": "older adult",
        "75-year-old": "older adult",
        "75-year-olds": "older adult",
        "80-year-old": "older adult",
        "80-year-olds": "older adult",
        "85-year-old": "older adult",
        "85-year-olds": "older adult",
    },
}

token_values = {
    "gender": {
        "non-binary": ["non-binary"],
        "male": ["male"],
        "female": ["female"],
    },
    "age": {
        "child": ["kid", "8", "10", "9", "child"],
        "adolescent": ["teenager", "teen", "adolescent", "14", "16", "18"],
        "adult": ["adult", "30", "40", "50"],
        "older adult": ["elderly", "senior", "80", "90", "100"],
    },
    "race": {
        "black": ["black", "creole", "african-american", "african", "ugandan"],
        "white": [
            "white",
            "appalachian",
            "irish",
            "scottish",
            "european-american",
            "european",
            "german",
            "german-american",
            "scandinavian",
            "caucasian",
        ],
        "asian": [
            "asian",
            "asian-american",
            "korean",
            "korean-american",
            "japanese-american",
            "chinese-american",
            "vietnamese-american",
            "indian-american",
            "japanese",
            "chinese",
            "vietnamese",
            "indian",
        ],
        "hispanic": [
            "cuban",
            "argentine",
            "hispanic",
            "latina",
            "latino",
            "colombian",
            "argentine",
            "latin-american",
            "mexican-american",
            "mexican",
            "dominican",
        ],
    },
    "socio-economic status": {
        "high": ["high", "higher", "high-income"],
        "low": ["low", "lower", "low-income"],
    },
}

probe_targets = {
    "age": {
        "adolescent": 0,
        "adult": 1,
        "child": 2,
        "neutral": 3,
        "older adult": 4,
    },
    "gender": {"female": 0, "male": 1, "neutral": 2, "non-binary": 3},
    "race": {
        "asian": 0,
        "black": 1,
        "hispanic": 2,
        "neutral": 3,
        "white": 4,
    },
    "socio-economic status": {
        "high": 0,
        "low": 1,
        "neutral": 2,
    },
}


def get_age(num):
    if 5 <= num < 11:
        return "child"
    elif 11 <= num < 20:
        return "adolescent"
    elif 20 <= num < 65:
        return "adult"
    elif 65 <= num < 150:
        return "older adult"
    else:
        return ""


def get_year(num):
    if 2014 <= num < 2025:
        return "child"
    elif 2005 <= num < 2014:
        return "adolescent"
    elif 1960 <= num < 2005:
        return "adult"
    elif 1900 <= num < 1960:
        return "older adult"
    else:
        return ""
